### ISSUE TITLE
Design Docs Checklist

### ISSUE THREAD

**Issue by taylormusolf** [chrisbanas/neighborhood_node#1]
# Wiki Home Page
- [ ] Is the first page you see upon entering the wiki
- [ ] Contains a welcome message
- [ ] Contains a link/placeholder for a link to the live page
- [ ] All links in the right sidebar should contain each wiki page and link to the correct page
- [ ] Correctly formatted
  - [ ] each wiki page is listed in bullet points
  - [ ] all links route the correct page
## Comments
---
# Feature List
- [ ] Should have 7 Features.
  - [ ] 3 of those are User Auth, Heroku, and Production README.
  - [ ] The other 4 are unique to this project
- [ ] Contains a description sentence of the app
- [ ] Includes two to three detailed bullets on functionality and presentation of feature
- [ ] At least one CRUD feature, which states what CRUD operations are planned (creation, reading, updating, deletion)
- [ ] Estimates how long it will take the code each Feature
- [ ] Correctly formatted
  - [ ] Features are listed in an ordered list
  - [ ] Each Feature is broken down into bullet points
## Comments
- you are missing a feature.  Possibly it could be Likes since you mention liking a post
---
# Database Schema
- [ ] Contains correct datatypes
- [ ] Contains appropriate constraints/details
  - [ ] primary key
  - [ ] not null
  - [ ] unique
  - [ ] indexed
  - [ ] foreign key
- [ ] Contains bullet points after the table that state which foreign keys will reference to which table, or references to the associations which will be made
 - [ ] foreign key and table name are lowercased, snake_cased and `back_ticked`
- [ ] Correctly formatted
  - [ ] schema is written in a table format
  - [ ] the table's name are lowercased, snake_cased and `back_ticked`
  - [ ] the table header column names are bolded
  - [ ] columns names are lowercased and snaked_cased and `back_ticked`
## Comments
- `password digest` does not need to be `unique` or `indexed`
- your tables are all currently the same
---
# Sample State
- [ ] State shape is flat!
- [ ] State's keys are camelCased
- [ ] All keys within the values in the state are accessible in the schema
- [ ] Correctly formatted
  - [ ] Sample state is rendered with triple backticks, and the language ` ```javascript...``` `). This will display the state as a code block instead of a giant line of text 
  - [ ] Top level slices
    - [ ] `entities`
    - [ ] `session`
    - [ ] `errors` (here or in `ui`)
    - [ ] `ui` (if needed)
  - [ ] Should NOT have nested slices, aka `comments` inside of `posts`
   + Some info from other tables is ok, for instance:
    + the author username and imageurl for a post. basically any info that the user can't change
    + like count and a boolean on whether the user likes the post instead of a likes slice
## Comments
- need to format the sample state so it is readable.  Put ` ```javascript` at the top and ` ``` ` at the bottom does this 
---
# Backend Routes
- [ ] Contains the following sections: HTML, API Endpoints(Backend)
- [ ] Each route has a description
- [ ] API Endpoint routes contains wildcard variables written in `snake_case`
- [ ] Routes does not contain superfluous routes
- [ ] Have API routes that will allow the front end to get all info it needs and does not have unneeded routes:
  + probably doesn't need a `GET likes` api endpoint because that info comes through the post show
## Comments
---
# Frontend Routes
- [ ] Frontend routes contains wildcard variables written in `camelCase`
- [ ] Correctly formatted
  - [ ] Routes are displayed with `inline coding text` (backticks)
## Comments

**Comment by taylormusolf** [comment]
@chrisbanas Take a look at the notes I left for you so far and the items I have left unchecked.  You have a lot going on in your Features doc so let me know if you want to talk about it.  I want to make sure the feature set you have decided on is manageable for you to get done.

**Comment by chrisbanas** [comment]
@taylormusolf , Hi Taylor. Thanks for reviewing and for the feedback. I changed some things on the MVP and Schema per your notes. On the sample state, I wasn't sure how to represent the count of votes per option so I just put the array. 

Also, on tonight's backend routes I was unsure what was needed and what Jbuilder could take away so, I just made everything I could think of and we can scale it back. I have a feeling comments are not needed and that can be done through the posts.

For the features, I listed everything I hope to accomplish which is why most are under bonus. In terms of just MVP features outside of the general user creation and profile stuff, I want to create a news feed where users can post. I was hoping to be able to have users attach images to their posts and also tag the geo-location. Then users can like/unlike and comment and then nest comments. Everything in the posts would have CRUD on it. Also, I would need to create neighborhoods but users cannot make these, they would be preset in the database or somewhere based on zip codes in the country and then users can just select their neighborhood based on their zip code. Everything else will be a bonus but I hope to get a private chat done and then tackle the groups and other things. I feel it shouldn't be too bad as they will mimic how posts are set up.

Again I know that there is a lot in the design docs. Part of it is I want to list everything out and the other is I'm not sure where I may have added too much. I'm hoping that by putting in the work now to create detailed design docs for everything I would like to implement that I can accomplish most of it.

I'm happy to chat about it tomorrow and put a little more direction to it.

**Comment by taylormusolf** [comment]
@chrisbanas I do appreciate how detailed you are being for your docs, but I want to make sure the core CRUD features will be prioritized and then you can jump into the others.  So I will want to see Feature #5 happen before 3 and 4.  We can chat about it when we meet.
